# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='community/logo'),
        ),
    ]
